### ISSUE TITLE
Node-monitor the open file - reload when changed

### ISSUE THREAD

**Issue by humdingerb** [andimachovec/Kottan#7]
It may be useful to have Kottan node-monitor the open file and pop up an alert:

```
'%filename%' has changed.
     [Cancel]   [Reload]
```

On a debugging session, you can just open the flattened message in Kottan and monitor changes without continuously having to close/reopen the file.

**Comment by andimachovec** [comment]
That would come in handy for sure. Reloading is not a problem at all, will have to check how node monitoring is done under Haiku. Most like I'll take a look at the source code of Koder, which is my unofficial "role model" for everything that I can't find in the haiku book or in the be book ;-)

**Comment by humdingerb** [comment]
Yeah, KapiX' work should be a good reference, also the apps and prefs in the Haiku source itself.

BTW, since you probably use Koder then, if you activate "Highlight trailing whitespace", you'll see how much of those is in Kottan. The option below should trim those on save, should you consider to clean up... :)

**Comment by andimachovec** [comment]
Thanks for the hint, I know I'm a bit careless with this in C++ code, since the preprocessor throws it all out the window at the first stage anyway. ;-) But you're right of course, it should be cleaned up.

**Comment by humdingerb** [comment]
Yeah. Another reason: whitespace is easily changed without noticing (I suppose that's also the reason Koder and Pe have options to remove that stuff on saving). That pollutes the commit diff needlessly.

**Comment by humdingerb** [comment]
Nice! Though it's not yet perfect. :)

Kottan should only offer to "Reload", if the contents of the file has actually changed. For example, open `/boot/home/config/settings/Tracker/tracker_shelf` in Kottan
Now, invoke the FileType Tracker Add-on on it. Kottan will offer to reload, even though nothing has changed. Not sure why the node monitor is triggered, but it is...

Same for everything that just rewrites its settings, no matter if anything has actually changed. For example, same scenario as above, this time quit Tracker via ProcessController.

**Comment by humdingerb** [comment]
Also, a "File | Reload (ALT+R)" may be useful, in case node monitoring isn't available. Maybe the file is on a non-BFS volume or a remotely mounted one.

**Comment by andimachovec** [comment]
> Nice! Though it's not yet perfect. :)

Thanks! You know, nothing is perfect ;-) I was too lazy to implement my own BMessage comparison algorithm, but I just found the BMessage class method HasSameData() which does exactly that. It is marked as experimental at the moment but I'm going to check it out. Of course I could have checked the flags returned from the node monitor if the file size changed but that's not a reliable indicator if the data in the message has actually changed.  

> Maybe the file is on a non-BFS volume

Come on, we're on Haiku not on Linux ;-) We're supposed to use BFS, despite all kinds of strange filesystems  getting half-implemented every year at GSOC. Sorry, drifting off topic here ;-) And just kidding of course. I'm going to add the manual reload option.

**Comment by humdingerb** [comment]
> but I just found the BMessage class method HasSameData() which does exactly that. It is marked as experimental at the moment but I'm going to check it out.

Good find! HasSameData() is apparently used in various places in the Haiku code, so I'd say it's save to use.

**Comment by andimachovec** [comment]
That's good to know. I've done some changes to the code that handles the notification. I check the stat flags returned from the node monitor message first and if the modification time has changed, the content of the file is compared to the loaded message. Only if there is a difference the reload dialog appear. You can check it out in the refine_nodemonitoring branch. 
I've left some debug output to the console in the code so you can see a bit more detail of what actually happens regarding to node monitoring.

**Comment by andimachovec** [comment]
> For example, open `/boot/home/config/settings/Tracker/tracker_shelf` in Kottan
> Now, invoke the FileType Tracker Add-on on it. Kottan will offer to reload, even though nothing has changed. Not sure why the node monitor is triggered, but it is...

I configured the node monitor to watch for B_STAT_CHANGED events, that is when the stat struct of the file changes. That includes changes to the access time which is likely what the FileTypes add-on caused

**Comment by humdingerb** [comment]
Seems to work nicely!

**Comment by andimachovec** [comment]
Great, that´s good to hear. I´m going to merge it and close the issue. If you run into any further problems with the reload notifications
